// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: employee_occupation.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmployeeOccupation = `-- name: CreateEmployeeOccupation :one
INSERT INTO
    "employee_occupation" ("name", "description")
VALUES
    ($1, $2) RETURNING id, name, description
`

type CreateEmployeeOccupationParams struct {
	Name        string      `db:"name"`
	Description pgtype.Text `db:"description"`
}

func (q *Queries) CreateEmployeeOccupation(ctx context.Context, arg CreateEmployeeOccupationParams) (EmployeeOccupation, error) {
	row := q.db.QueryRow(ctx, createEmployeeOccupation, arg.Name, arg.Description)
	var i EmployeeOccupation
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const deleteEmployeeOccupation = `-- name: DeleteEmployeeOccupation :one
DELETE FROM
    "employee_occupation"
WHERE
    "id" = $1 RETURNING id, name, description
`

func (q *Queries) DeleteEmployeeOccupation(ctx context.Context, id int32) (EmployeeOccupation, error) {
	row := q.db.QueryRow(ctx, deleteEmployeeOccupation, id)
	var i EmployeeOccupation
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const listEmployeeOccupations = `-- name: ListEmployeeOccupations :many
SELECT
    employee_occupation.id, employee_occupation.name, employee_occupation.description,
    COUNT("employee"."id") AS "count"
FROM
    "employee_occupation"
    LEFT JOIN "employee" ON "employee"."occupation_id" = "employee_occupation"."id"
GROUP BY
    "employee_occupation"."id"
ORDER BY
    "employee_occupation"."id" ASC
`

type ListEmployeeOccupationsRow struct {
	ID          int32       `db:"id"`
	Name        string      `db:"name"`
	Description pgtype.Text `db:"description"`
	Count       int64       `db:"count"`
}

func (q *Queries) ListEmployeeOccupations(ctx context.Context) ([]ListEmployeeOccupationsRow, error) {
	rows, err := q.db.Query(ctx, listEmployeeOccupations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeeOccupationsRow{}
	for rows.Next() {
		var i ListEmployeeOccupationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmployeeOccupation = `-- name: UpdateEmployeeOccupation :one
UPDATE
    "employee_occupation"
SET
    "name" = COALESCE($1, name),
    "description" = $2
WHERE
    "id" = $3 RETURNING id, name, description
`

type UpdateEmployeeOccupationParams struct {
	Name        pgtype.Text `db:"name"`
	Description pgtype.Text `db:"description"`
	ID          int32       `db:"id"`
}

func (q *Queries) UpdateEmployeeOccupation(ctx context.Context, arg UpdateEmployeeOccupationParams) (EmployeeOccupation, error) {
	row := q.db.QueryRow(ctx, updateEmployeeOccupation, arg.Name, arg.Description, arg.ID)
	var i EmployeeOccupation
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}
