// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: holiday_date.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type CreateHolidayDatesParams struct {
	Date      pgtype.Date `db:"date"`
	HolidayID int32       `db:"holiday_id"`
}

const deleteHolidayDateByHolidayId = `-- name: DeleteHolidayDateByHolidayId :exec
DELETE FROM
    "holiday_date"
WHERE
    "holiday_id" = $1
`

func (q *Queries) DeleteHolidayDateByHolidayId(ctx context.Context, holidayID int32) error {
	_, err := q.db.Exec(ctx, deleteHolidayDateByHolidayId, holidayID)
	return err
}
