DROP FUNCTION IF EXISTS list_santri CASCADE;
DROP FUNCTION IF EXISTS list_user CASCADE;
DROP FUNCTION IF EXISTS list_parent CASCADE;
DROP FUNCTION IF EXISTS list_employee CASCADE;

DROP TYPE IF EXISTS santri_order_by CASCADE;
DROP TYPE IF EXISTS user_order_by CASCADE;
DROP TYPE IF EXISTS parent_order_by CASCADE;
DROP TYPE IF EXISTS employee_order_by CASCADE;
DROP TYPE IF EXISTS card_owner CASCADE;