// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: employee_occupation.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmployeeOccupation = `-- name: CreateEmployeeOccupation :one
INSERT INTO "employee_occupation" ("name", "description") VALUES ($1, $2) RETURNING id, name, description
`

type CreateEmployeeOccupationParams struct {
	Name        string
	Description pgtype.Text
}

func (q *Queries) CreateEmployeeOccupation(ctx context.Context, arg CreateEmployeeOccupationParams) (EmployeeOccupation, error) {
	row := q.db.QueryRow(ctx, createEmployeeOccupation, arg.Name, arg.Description)
	var i EmployeeOccupation
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const deleteEmployeeOccupation = `-- name: DeleteEmployeeOccupation :one
DELETE FROM "employee_occupation" WHERE "id" = $1 RETURNING id, name, description
`

func (q *Queries) DeleteEmployeeOccupation(ctx context.Context, id int32) (EmployeeOccupation, error) {
	row := q.db.QueryRow(ctx, deleteEmployeeOccupation, id)
	var i EmployeeOccupation
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const listEmployeeOccupations = `-- name: ListEmployeeOccupations :many
SELECT 
    id, name, description,
    COUNT(*) OVER () AS "count"
FROM 
    "employee_occupation"
`

type ListEmployeeOccupationsRow struct {
	ID          int32
	Name        string
	Description pgtype.Text
	Count       int64
}

func (q *Queries) ListEmployeeOccupations(ctx context.Context) ([]ListEmployeeOccupationsRow, error) {
	rows, err := q.db.Query(ctx, listEmployeeOccupations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeeOccupationsRow{}
	for rows.Next() {
		var i ListEmployeeOccupationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmployeeOccupation = `-- name: UpdateEmployeeOccupation :one
UPDATE "employee_occupation" SET "name" = $1, "description" = $2 WHERE "id" = $3 RETURNING id, name, description
`

type UpdateEmployeeOccupationParams struct {
	Name        string
	Description pgtype.Text
	ID          int32
}

func (q *Queries) UpdateEmployeeOccupation(ctx context.Context, arg UpdateEmployeeOccupationParams) (EmployeeOccupation, error) {
	row := q.db.QueryRow(ctx, updateEmployeeOccupation, arg.Name, arg.Description, arg.ID)
	var i EmployeeOccupation
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}
