// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CountParents(ctx context.Context, arg CountParentsParams) (int64, error)
	CountUsers(ctx context.Context, arg CountUsersParams) (int64, error)
	CreateArduino(ctx context.Context, name string) (Arduino, error)
	CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error)
	CreateEmployeeOccupation(ctx context.Context, arg CreateEmployeeOccupationParams) (EmployeeOccupation, error)
	CreateHoliday(ctx context.Context, arg CreateHolidayParams) (Holiday, error)
	CreateHolidayDay(ctx context.Context, arg CreateHolidayDayParams) (HolidayDay, error)
	CreateParent(ctx context.Context, arg CreateParentParams) (Parent, error)
	CreateSantri(ctx context.Context, arg CreateSantriParams) (Santri, error)
	CreateSantriOccupation(ctx context.Context, arg CreateSantriOccupationParams) (SantriOccupation, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteArduino(ctx context.Context, id int32) (Arduino, error)
	DeleteEmployee(ctx context.Context, id int32) (Employee, error)
	DeleteEmployeeOccupation(ctx context.Context, id int32) (EmployeeOccupation, error)
	DeleteHoliday(ctx context.Context, id int32) (Holiday, error)
	DeleteHolidayDay(ctx context.Context, id int32) (HolidayDay, error)
	DeleteParent(ctx context.Context, id int32) (Parent, error)
	DeleteSantri(ctx context.Context, id int32) (Santri, error)
	DeleteSantriOccupation(ctx context.Context, id int32) (SantriOccupation, error)
	DeleteUser(ctx context.Context, id int32) (User, error)
	GetEmployee(ctx context.Context, id int32) (GetEmployeeRow, error)
	GetParent(ctx context.Context, id int32) (GetParentRow, error)
	GetSantri(ctx context.Context, id int32) (GetSantriRow, error)
	GetUserByID(ctx context.Context, id int32) (GetUserByIDRow, error)
	QueryArduino(ctx context.Context, arg QueryArduinoParams) ([]Arduino, error)
	QueryEmployeeOccupations(ctx context.Context) ([]QueryEmployeeOccupationsRow, error)
	QueryEmployeesAsc(ctx context.Context, arg QueryEmployeesAscParams) ([]QueryEmployeesAscRow, error)
	QueryHolidayDays(ctx context.Context, arg QueryHolidayDaysParams) ([]QueryHolidayDaysRow, error)
	QueryParentsAsc(ctx context.Context, arg QueryParentsAscParams) ([]QueryParentsAscRow, error)
	QueryParentsDesc(ctx context.Context, arg QueryParentsDescParams) ([]QueryParentsDescRow, error)
	QuerySantriAscGeneration(ctx context.Context, arg QuerySantriAscGenerationParams) ([]QuerySantriAscGenerationRow, error)
	QuerySantriAscName(ctx context.Context, arg QuerySantriAscNameParams) ([]QuerySantriAscNameRow, error)
	QuerySantriAscNis(ctx context.Context, arg QuerySantriAscNisParams) ([]QuerySantriAscNisRow, error)
	QuerySantriAscOccupation(ctx context.Context, arg QuerySantriAscOccupationParams) ([]QuerySantriAscOccupationRow, error)
	QuerySantriOccupations(ctx context.Context) ([]QuerySantriOccupationsRow, error)
	QueryUsersAscUsername(ctx context.Context, arg QueryUsersAscUsernameParams) ([]QueryUsersAscUsernameRow, error)
	QueryUsersDescUsername(ctx context.Context, arg QueryUsersDescUsernameParams) ([]QueryUsersDescUsernameRow, error)
	UpdateArduino(ctx context.Context, arg UpdateArduinoParams) (Arduino, error)
	UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (Employee, error)
	UpdateEmployeeOccupation(ctx context.Context, arg UpdateEmployeeOccupationParams) (EmployeeOccupation, error)
	UpdateHoliday(ctx context.Context, arg UpdateHolidayParams) (Holiday, error)
	UpdateParent(ctx context.Context, arg UpdateParentParams) (Parent, error)
	UpdateSantri(ctx context.Context, arg UpdateSantriParams) (Santri, error)
	UpdateSantriOccupation(ctx context.Context, arg UpdateSantriOccupationParams) (SantriOccupation, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
