// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: santri_presence.sql

package persistence

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSantriPresence = `-- name: CreateSantriPresence :one
INSERT INTO
    "santri_presence" (
        "schedule_id",
        "schedule_name",
        "type",
        "santri_id",
        "notes",
        "created_by",
        "santri_permission_id"
    )
VALUES
    (
        $1,
        $2,
        $3 :: presence_type,
        $4,
        $5,
        $6 :: presence_created_by,
        $7
    ) RETURNING id, schedule_id, schedule_name, type, santri_id, created_at, created_by, notes, santri_permission_id
`

type CreateSantriPresenceParams struct {
	ScheduleID         int32             `db:"schedule_id" json:"schedule_id"`
	ScheduleName       string            `db:"schedule_name" json:"schedule_name"`
	Type               PresenceType      `db:"type" json:"type"`
	SantriID           int32             `db:"santri_id" json:"santri_id"`
	Notes              pgtype.Text       `db:"notes" json:"notes"`
	CreatedBy          PresenceCreatedBy `db:"created_by" json:"created_by"`
	SantriPermissionID pgtype.Int4       `db:"santri_permission_id" json:"santri_permission_id"`
}

func (q *Queries) CreateSantriPresence(ctx context.Context, arg CreateSantriPresenceParams) (SantriPresence, error) {
	row := q.db.QueryRow(ctx, createSantriPresence,
		arg.ScheduleID,
		arg.ScheduleName,
		arg.Type,
		arg.SantriID,
		arg.Notes,
		arg.CreatedBy,
		arg.SantriPermissionID,
	)
	var i SantriPresence
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.ScheduleName,
		&i.Type,
		&i.SantriID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.Notes,
		&i.SantriPermissionID,
	)
	return i, err
}

const deleteSantriPresence = `-- name: DeleteSantriPresence :one
DELETE FROM
    "santri_presence"
WHERE
    "id" = $1
RETURNING id, schedule_id, schedule_name, type, santri_id, created_at, created_by, notes, santri_permission_id
`

func (q *Queries) DeleteSantriPresence(ctx context.Context, id pgtype.Int4) (SantriPresence, error) {
	row := q.db.QueryRow(ctx, deleteSantriPresence, id)
	var i SantriPresence
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.ScheduleName,
		&i.Type,
		&i.SantriID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.Notes,
		&i.SantriPermissionID,
	)
	return i, err
}

const listSantriPresences = `-- name: ListSantriPresences :many
SELECT
    santri_presence.id, schedule_id, schedule_name, type, santri_id, created_at, created_by, notes, santri_permission_id, santri.id, nis, name, gender, generation, is_active, photo, occupation_id, parent_id
FROM
    "santri_presence"
    INNER JOIN "santri" ON "santri_presence"."santri_id" = "santri"."id"
WHERE
    (
        $1 :: integer IS NULL
        OR "santri_id" = $1 :: integer
    )
    AND (
        $2 :: text IS NULL
        OR "santri"."name" ILIKE '%' || $2 || '%'
    )
    AND (
        $3 :: presence_type IS NULL
        OR "type" = $3 :: presence_type
    )
    AND (
        $4 :: integer IS NULL
        OR "schedule_id" = $4 :: integer
    )
    AND (
        $5 :: timestamp IS NULL
        OR "created_at" >= $5 :: timestamp
    )
    AND (
        $6 :: timestamp IS NULL
        OR "created_at" <= $6 :: timestamp
    )
LIMIT
    $8 OFFSET $7
`

type ListSantriPresencesParams struct {
	SantriID     pgtype.Int4      `db:"santri_id" json:"santri_id"`
	Q            pgtype.Text      `db:"q" json:"q"`
	Type         NullPresenceType `db:"type" json:"type"`
	ScheduleID   pgtype.Int4      `db:"schedule_id" json:"schedule_id"`
	FromDate     pgtype.Timestamp `db:"from_date" json:"from_date"`
	ToDate       pgtype.Timestamp `db:"to_date" json:"to_date"`
	OffsetNumber int32            `db:"offset_number" json:"offset_number"`
	LimitNumber  int32            `db:"limit_number" json:"limit_number"`
}

type ListSantriPresencesRow struct {
	ID                 pgtype.Int4        `db:"id" json:"id"`
	ScheduleID         int32              `db:"schedule_id" json:"schedule_id"`
	ScheduleName       string             `db:"schedule_name" json:"schedule_name"`
	Type               PresenceType       `db:"type" json:"type"`
	SantriID           int32              `db:"santri_id" json:"santri_id"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy          PresenceCreatedBy  `db:"created_by" json:"created_by"`
	Notes              pgtype.Text        `db:"notes" json:"notes"`
	SantriPermissionID pgtype.Int4        `db:"santri_permission_id" json:"santri_permission_id"`
	ID_2               int32              `db:"id_2" json:"id_2"`
	Nis                pgtype.Text        `db:"nis" json:"nis"`
	Name               string             `db:"name" json:"name"`
	Gender             Gender             `db:"gender" json:"gender"`
	Generation         int32              `db:"generation" json:"generation"`
	IsActive           pgtype.Bool        `db:"is_active" json:"is_active"`
	Photo              pgtype.Text        `db:"photo" json:"photo"`
	OccupationID       pgtype.Int4        `db:"occupation_id" json:"occupation_id"`
	ParentID           pgtype.Int4        `db:"parent_id" json:"parent_id"`
}

func (q *Queries) ListSantriPresences(ctx context.Context, arg ListSantriPresencesParams) ([]ListSantriPresencesRow, error) {
	rows, err := q.db.Query(ctx, listSantriPresences,
		arg.SantriID,
		arg.Q,
		arg.Type,
		arg.ScheduleID,
		arg.FromDate,
		arg.ToDate,
		arg.OffsetNumber,
		arg.LimitNumber,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSantriPresencesRow{}
	for rows.Next() {
		var i ListSantriPresencesRow
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleID,
			&i.ScheduleName,
			&i.Type,
			&i.SantriID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.Notes,
			&i.SantriPermissionID,
			&i.ID_2,
			&i.Nis,
			&i.Name,
			&i.Gender,
			&i.Generation,
			&i.IsActive,
			&i.Photo,
			&i.OccupationID,
			&i.ParentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSantriPresence = `-- name: UpdateSantriPresence :one
UPDATE
    "santri_presence"
SET
    "schedule_id" = $1,
    "schedule_name" = $2,
    "type" = $3::presence_type,
    "santri_id" = $4,
    "notes" = $5,
    "santri_permission_id" = $6
WHERE
    "id" = $7
    RETURNING id, schedule_id, schedule_name, type, santri_id, created_at, created_by, notes, santri_permission_id
`

type UpdateSantriPresenceParams struct {
	ScheduleID         int32        `db:"schedule_id" json:"schedule_id"`
	ScheduleName       string       `db:"schedule_name" json:"schedule_name"`
	Type               PresenceType `db:"type" json:"type"`
	SantriID           int32        `db:"santri_id" json:"santri_id"`
	Notes              pgtype.Text  `db:"notes" json:"notes"`
	SantriPermissionID pgtype.Int4  `db:"santri_permission_id" json:"santri_permission_id"`
	ID                 pgtype.Int4  `db:"id" json:"id"`
}

func (q *Queries) UpdateSantriPresence(ctx context.Context, arg UpdateSantriPresenceParams) (SantriPresence, error) {
	row := q.db.QueryRow(ctx, updateSantriPresence,
		arg.ScheduleID,
		arg.ScheduleName,
		arg.Type,
		arg.SantriID,
		arg.Notes,
		arg.SantriPermissionID,
		arg.ID,
	)
	var i SantriPresence
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.ScheduleName,
		&i.Type,
		&i.SantriID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.Notes,
		&i.SantriPermissionID,
	)
	return i, err
}
